theme: jekyll-theme-minimal
title: Gwangmu Lee
logo: gwangmu.jpg
is_project_page: false
description: |
  Loc: Room 653-1, Bldg. 301, Gwanak-ro 1, Gwanak-gu, Seoul, Korea Republic. (PO 08826) |
  Tel: +82 10 4114 7441 |
  E-mail: gwangmu@snu.ac.kr
