# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gwangmu Lee 
title: PhD Student in Computer Security
email: gwangmu@snu.ac.kr
website: gwangmu.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
stackoverflow_username: "5085424"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: cassert24
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# reddit_username: cassert

# Additional icon links
additional_links:
- title: Reddit link
  icon: fab fa-reddit-alien
  url: https://www.reddit.com/user/cassert24
# - title: E-mail
#  icon: far fa-envelope
#  url: "mailto:gwangmu@snu.ac.kr"
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/gwangmu.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there! I'm a PhD student at Seoul National University (SNU). 
  I'm currently interested in various <mark>computer security</mark> issues, especially in fuzz testing. 
  I have previously studied <mark>compiler techniques</mark> such as offloading 
  and <mark>computer architecture</mark> issues like neuromorphic computing. 
  Please visit [System Security Laboratory (compsec)](http://compsec.snu.ac.kr), 
  my research group led by my advisor [Byoungyoung Lee](http://lifeasageek.github.io), 
  for more ongoing security-related research topics.

content:
  #- title: Education # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Harvard University
  #      caption: 2010 - 2013
  #      sub_title: BSc Computer Science
  #      quote: >
  #        Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #      description: | # this will include new lines to allow paragraphs
  #        During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
  #
  #        I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left 
        title: POSTECH
        caption: Mar 2010 - Aug 2014
        sub_title: B.S. in Physics & Computer Science and Engineering
        additional_links:
          - title: Department of Physics
            icon: fas fa-atom
            url: https://ph.postech.ac.kr
          - title: Department of Computer Science and Engineering 
            icon: fas fa-laptop-code
            url: https://cse.postech.ac.kr
        quote: >
          Pohang University of Science and Technology (POSTECH) is a research university in Pohang, South Korea.
          Founded in 1986, POSTECH has been maintaining its reputation as one of the most prominent young universities in the world, being 1st in Times Higher Education "100 Under 50 Young Univ." rankings 2014.
        description: >
          I started my college years with the physics major, but I grew my interest in computer science while developing indie video games with Microsoft XNA.
          After finding myself more enthusiastic to computer engineering than physics, I decided to double-major computer engineering and take the path as a computer engineer. 

      - layout: left 
        title: POSTECH
        caption: Sep 2014 - Feb 2017
        sub_title: M.S. in Computer Science and Engineering 
        additional_links:
          - title: Department of Computer Science and Engineering 
            icon: fas fa-laptop-code
            url: https://cse.postech.ac.kr
        description: > 
          During my first few graduate years, I studied various <mark>compiler techniques</mark> using LLVM and published my first conference paper about computation offloading in MICRO.
          Later, I switched my interest to <mark>computer architecture</mark> and worked on designing energy-efficient neuromorphic circuits.

      - layout: left 
        title: Seoul National University
        caption: Mar 2017 - Present
        sub_title: PhD Student in Electrical and Computer Engineering
        additional_links:
          - title: Department of Electrical and Computer Engineering 
            icon: fas fa-microchip
            url: https://ee.snu.ac.kr
        quote: >
          Seoul National University (SNU) is a national research university located in Seoul, South Korea.
          Founded in 1946, Seoul National University is considered to be the most prestigious university in the country.
        description: >
          I'm currently pursuing my PhD degree in <mark>computer security</mark>. 
          By leveraging my expertise on compilers and computer systems, I'm currently aiming at building a system-wide fuzzing framework that encompasses the entire software stack, including user applications and OS kernels.

  - title: Publications
    layout: list
    content:
      - layout: top-middle
        title: "Constraint-guided Directed Greybox Fuzzing"
        caption: >
          Gwangmu Lee, Woochul Shim, and Byoungyoung Lee  
        quote: >
          The 30th USENIX Security Symposium (Security), August 2021 [to appear]

      - layout: top-middle
        title: "Flexon: A Cost-Effective Digital Neuron for Flexible Spiking Neural Network Simulation" 
        caption: >
          Dayeol Lee, Gwangmu Lee, Sunghwa Lee, Dongup Kwon, Youngsok Kim, and Jangwoo Kim  
        quote: >
          The 45th International Symposium on Computer Architecture (ISCA), June 2018

      - layout: top-middle
        title: "DynaMix: Dynamic Mobile Device Integration for Efficient Cross-device Resource Sharing" 
        link_text: >
        caption: >
          Dongju Chae, Joonsung Kim, Gwangmu Lee, Hanjun Kim, Kyung-Ah Chang, Hyogun Lee, and Jangwoo Kim  
        quote: >
          2018 USENIX Annual Technical Conference (ATC), June 2018

      - layout: top-middle
        title: Architecture-aware Automatic Computation Offload for Native Applications  
        caption: >
          Gwangmu Lee, Hyunjoon Park, Seonyeong Heo, Kyung-Ah Chang, Hyogun Lee, and Hanjun Kim  
        quote: >
          The 48th Annual IEEE/ACM International Symposium on Microarchitecture (MICRO), December 2015

  - title: Recognition
    layout: list
    content:
      - layout: top-middle
        title: "26th Graduate Scholarship Student" 
        caption: >
          March 2015 - February 2020
        quote: >
          Korea Foundation for Advanced Study (KFAS)

      - layout: top-middle
        title: "National Science and Engineering Scholarship"
        caption: >
          March 2010 - February 2014
        quote: >
          Korea Student Aid Foundation (KOSAF)

  - title: Teaching Experience 
    layout: list 
    content:
      - layout: top-middle 
        title: Computer Organization
        caption: Teaching Assistant
        quote: >
          Spring 2016 (POSTECH), Spring 2017/2020 (SNU) 

      - layout: top-middle 
        title: Digital Logic Design
        caption: Teaching Assistant
        quote: >
          Fall 2017 (SNU)

      - layout: top-middle 
        title: Object Oriented Programming
        caption: Teaching Assistant
        quote: >
          Fall 2015 (POSTECH)

  - title: Miscellaneous Stuff 
    layout: list 
    content: 
      - layout: left 
        title: Jokebox 
        caption: Game development framework for C/C++ beginners
        additional_links:
          - title: Jokebox blog
            icon: fas fa-globe
            url: https://jokebox24.blog.me
        description: |
          During when I was a committee member of the college game development group,
          there were not many game development tools for people who are not accustomed to
          programming. This was especially a tough challenge for a college group, as lots of
          new members (i.e., freshmens) do not have preliminary knowledge of basic programming.
          This prompted me to design a simple game development framework (essentially a Direct 11
          wrapper) that any new C/C++ beginners can easily access.

          Now that there are many convenient game development tools like Unity,
          this framework is arguably no longer relevant, but I thought it's worth mentioning here
          as my first attempt to solve a real problem with a software solution.

# Footer
footer_show_references: true
references_title: >
  Last update: February 9th, 2021

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
